import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';

const css = (await readFile('app/styles.css', 'utf8')) + (await readFile('app/overrides.css', 'utf8'));
const heroImage = (await readFile('public/hero-building-transparent.png')).toString('base64');
const heroCss = `.house{background-image:url(data:image/png;base64,${heroImage})}`;
let html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Немецкая слобода — экскурсия</title><style>${css}${heroCss}</style></head><body><main>
<section class="hero"><div class="topline"><span>ПЕШИЕ ИСТОРИИ</span><span>МОСКВА · 25 ИЮЛЯ</span></div><div class="hero-copy"><p class="eyebrow">ОКТЯБРЬСКОЕ ПОЛЕ</p><h1>Немецкая<br><i>слобода</i></h1><p class="lead">Неспешная прогулка по району с историей, вопросами и вишнёвым фильтром.</p><a class="cta" href="#booking">Выбрать время <span>↓</span></a></div><div class="stamp">25<br><small>ИЮЛЯ</small></div><div class="house"><div class="roof"></div><div class="facade"><span></span><span></span><span></span><span></span><span></span><span></span></div></div></section>
<section class="about"><p class="section-label">ЧТО ТЕБЯ ЖДЁТ</p><div class="about-grid"><h2>Квартал,<br>который<br><i>выделяется</i><br>изяществом форм<br>и уютом.</h2><div><p>Ты познакомишься с «немецкой слободой» — её атмосферой, деталями и историями. Гид проведёт по маршруту, а ты сможешь задать любые вопросы.</p><p>В прогулку входит дегустация вишнёвого фильтра. А если захочешь продолжить знакомство со вкусами, попробуешь и другие напитки из коллекции.</p></div></div></section>
<section class="details"><div><span>КОГДА</span><strong>25 июля</strong></div><div><span>ДЛИТЕЛЬНОСТЬ</span><strong>2 часа</strong></div><div><span>ВСТРЕЧА</span><strong>м. «Октябрьское поле»<br>выход 2</strong></div></section>
<section id="booking" class="booking"><div><p class="section-label">ЗАПИСЬ НА ПРОГУЛКУ</p><h2>Выбери<br><i>свой маршрут.</i></h2><p class="note">Оставь телефон — только чтобы не потеряться в день экскурсии.</p></div><form id="form"><label>ВРЕМЯ ПРОГУЛКИ</label><div class="slots"><button type="button">10:00–12:00</button><button type="button">12:00–14:00</button><button type="button">14:00–16:00</button><button type="button">16:00–18:00</button><button type="button">18:00–20:00</button></div><label for="phone">НОМЕР ТЕЛЕФОНА</label><input id="phone" required placeholder="+7 (___) ___-__-__" type="tel"><label class="check"><input id="consent" required type="checkbox"><span>Даю согласие на обработку персональных данных</span></label><button class="submit" type="submit">Забронируй место</button><p id="success" class="success" hidden></p></form></section><footer>НЕМЕЦКАЯ СЛОБОДА <span>·</span> МОСКВА <span>·</span> 2026</footer></main>
<script>let slot='';document.querySelectorAll('.slots button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slots button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');slot=b.textContent});document.querySelector('#form').onsubmit=e=>{e.preventDefault();if(!slot){alert('Выбери время прогулки');return}const s=document.querySelector('#success');s.hidden=false;s.textContent='Ты записан(а) на '+slot+'. Мы свяжемся с тобой по указанному номеру.';e.currentTarget.querySelector('.submit').textContent='Ты записан(а) — до встречи!'}</script></body></html>`;
html = html.replace('и уютом.', 'и уютом').replace('свой маршрут.</i>', 'свой маршрут</i>').replace('ВРЕМЯ ПРОГУЛКИ</label>', '25 ИЮЛЯ · ВРЕМЯ ПРОГУЛКИ</label>').replace('</body>', `<script>document.querySelector('#form').onsubmit=async e=>{e.preventDefault();if(!slot){alert('Выбери время прогулки');return}const button=e.currentTarget.querySelector('.submit');button.disabled=true;try{const r=await fetch('/api/book',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slot,phone:document.querySelector('#phone').value,consent:document.querySelector('#consent').checked})});if(!r.ok)throw new Error();const s=document.querySelector('#success');s.hidden=false;s.textContent='Ты записан(а) на '+slot+'. Мы свяжемся с тобой по указанному номеру.';button.textContent='Ты записан(а) — до встречи!'}catch{alert('Не удалось отправить заявку. Попробуй ещё раз позже.');button.disabled=false}}</script></body>`);
// Vercel serves files from public directly; keep this artifact alongside the
// existing Worker output so both hosting options use precisely the same page.
await writeFile('public/index.html', html);
await mkdir('dist/server', { recursive: true });
const worker = `const page=${JSON.stringify(html)};export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/book'&&request.method==='POST'){try{const data=await request.json();if(!data.slot||!data.phone||!data.consent)return Response.json({error:'invalid'},{status:400});if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return Response.json({error:'not configured'},{status:503});const text='Новая заявка — Немецкая слобода\\nДата: 25 июля\\nВремя: '+data.slot+'\\nТелефон: '+data.phone;const sent=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text})});if(!sent.ok)throw new Error('telegram');return Response.json({ok:true})}catch{return Response.json({error:'send failed'},{status:500})}}return new Response(page,{headers:{'content-type':'text/html; charset=UTF-8'}})}};`;
await writeFile('dist/server/index.js', worker);
