import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';

const css = (await readFile('app/styles.css', 'utf8')) + (await readFile('app/overrides.css', 'utf8'));
const heroImage = (await readFile('public/hero-building-transparent.png')).toString('base64');
const heroCss = `.house{background-image:url(data:image/png;base64,${heroImage})}`;
let html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>РќРµРјРµС†РєР°СЏ СЃР»РѕР±РѕРґР° вЂ” СЌРєСЃРєСѓСЂСЃРёСЏ</title><style>${css}${heroCss}</style></head><body><main>
<section class="hero"><div class="topline"><span>РџР•РЁРР• РРЎРўРћР РР</span><span>РњРћРЎРљР’Рђ В· 25 РР®Р›РЇ</span></div><div class="hero-copy"><p class="eyebrow">РћРљРўРЇР‘Р Р¬РЎРљРћР• РџРћР›Р•</p><h1>РќРµРјРµС†РєР°СЏ<br><i>СЃР»РѕР±РѕРґР°</i></h1><p class="lead">РќРµСЃРїРµС€РЅР°СЏ РїСЂРѕРіСѓР»РєР° РїРѕ СЂР°Р№РѕРЅСѓ СЃ РёСЃС‚РѕСЂРёРµР№, РІРѕРїСЂРѕСЃР°РјРё Рё РІРёС€РЅС‘РІС‹Рј С„РёР»СЊС‚СЂРѕРј.</p><a class="cta" href="#booking">Р’С‹Р±СЂР°С‚СЊ РІСЂРµРјСЏ <span>в†“</span></a></div><div class="stamp">25<br><small>РР®Р›РЇ</small></div><div class="house"><div class="roof"></div><div class="facade"><span></span><span></span><span></span><span></span><span></span><span></span></div></div></section>
<section class="about"><p class="section-label">Р§РўРћ РўР•Р‘РЇ Р–Р”РЃРў</p><div class="about-grid"><h2>РљРІР°СЂС‚Р°Р»,<br>РєРѕС‚РѕСЂС‹Р№<br><i>РІС‹РґРµР»СЏРµС‚СЃСЏ</i><br>РёР·СЏС‰РµСЃС‚РІРѕРј С„РѕСЂРј<br>Рё СѓСЋС‚РѕРј.</h2><div><p>РўС‹ РїРѕР·РЅР°РєРѕРјРёС€СЊСЃСЏ СЃ В«РЅРµРјРµС†РєРѕР№ СЃР»РѕР±РѕРґРѕР№В» вЂ” РµС‘ Р°С‚РјРѕСЃС„РµСЂРѕР№, РґРµС‚Р°Р»СЏРјРё Рё РёСЃС‚РѕСЂРёСЏРјРё. Р“РёРґ РїСЂРѕРІРµРґС‘С‚ РїРѕ РјР°СЂС€СЂСѓС‚Сѓ, Р° С‚С‹ СЃРјРѕР¶РµС€СЊ Р·Р°РґР°С‚СЊ Р»СЋР±С‹Рµ РІРѕРїСЂРѕСЃС‹.</p><p>Р’ РїСЂРѕРіСѓР»РєСѓ РІС…РѕРґРёС‚ РґРµРіСѓСЃС‚Р°С†РёСЏ РІРёС€РЅС‘РІРѕРіРѕ С„РёР»СЊС‚СЂР°. Рђ РµСЃР»Рё Р·Р°С…РѕС‡РµС€СЊ РїСЂРѕРґРѕР»Р¶РёС‚СЊ Р·РЅР°РєРѕРјСЃС‚РІРѕ СЃРѕ РІРєСѓСЃР°РјРё, РїРѕРїСЂРѕР±СѓРµС€СЊ Рё РґСЂСѓРіРёРµ РЅР°РїРёС‚РєРё РёР· РєРѕР»Р»РµРєС†РёРё.</p></div></div></section>
<section class="details"><div><span>РљРћР“Р”Рђ</span><strong>25 РёСЋР»СЏ</strong></div><div><span>Р”Р›РРўР•Р›Р¬РќРћРЎРўР¬</span><strong>2 С‡Р°СЃР°</strong></div><div><span>Р’РЎРўР Р•Р§Рђ</span><strong>Рј. В«РћРєС‚СЏР±СЂСЊСЃРєРѕРµ РїРѕР»РµВ»<br>РІС‹С…РѕРґ 2</strong></div></section>
<section id="booking" class="booking"><div><p class="section-label">Р—РђРџРРЎР¬ РќРђ РџР РћР“РЈР›РљРЈ</p><h2>Р’С‹Р±РµСЂРё<br><i>СЃРІРѕР№ РјР°СЂС€СЂСѓС‚.</i></h2><p class="note">РћСЃС‚Р°РІСЊ С‚РµР»РµС„РѕРЅ вЂ” С‚РѕР»СЊРєРѕ С‡С‚РѕР±С‹ РЅРµ РїРѕС‚РµСЂСЏС‚СЊСЃСЏ РІ РґРµРЅСЊ СЌРєСЃРєСѓСЂСЃРёРё.</p></div><form id="form"><label>Р’Р Р•РњРЇ РџР РћР“РЈР›РљР</label><div class="slots"><button type="button">10:00вЂ“12:00</button><button type="button">12:00вЂ“14:00</button><button type="button">14:00вЂ“16:00</button><button type="button">16:00вЂ“18:00</button><button type="button">18:00вЂ“20:00</button></div><label for="phone">РќРћРњР•Р  РўР•Р›Р•Р¤РћРќРђ</label><input id="phone" required placeholder="+7 (___) ___-__-__" type="tel"><label class="check"><input id="consent" required type="checkbox"><span>Р”Р°СЋ СЃРѕРіР»Р°СЃРёРµ РЅР° РѕР±СЂР°Р±РѕС‚РєСѓ РїРµСЂСЃРѕРЅР°Р»СЊРЅС‹С… РґР°РЅРЅС‹С…</span></label><button class="submit" type="submit">Р—Р°Р±СЂРѕРЅРёСЂСѓР№ РјРµСЃС‚Рѕ</button><p id="success" class="success" hidden></p></form></section><footer>РќР•РњР•Р¦РљРђРЇ РЎР›РћР‘РћР”Рђ <span>В·</span> РњРћРЎРљР’Рђ <span>В·</span> 2026</footer></main>
<script>let slot='';document.querySelectorAll('.slots button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slots button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');slot=b.textContent});document.querySelector('#form').onsubmit=e=>{e.preventDefault();if(!slot){alert('Р’С‹Р±РµСЂРё РІСЂРµРјСЏ РїСЂРѕРіСѓР»РєРё');return}const s=document.querySelector('#success');s.hidden=false;s.textContent='РўС‹ Р·Р°РїРёСЃР°РЅ(Р°) РЅР° '+slot+'. РњС‹ СЃРІСЏР¶РµРјСЃСЏ СЃ С‚РѕР±РѕР№ РїРѕ СѓРєР°Р·Р°РЅРЅРѕРјСѓ РЅРѕРјРµСЂСѓ.';e.currentTarget.querySelector('.submit').textContent='РўС‹ Р·Р°РїРёСЃР°РЅ(Р°) вЂ” РґРѕ РІСЃС‚СЂРµС‡Рё!'}</script></body></html>`;
html = html.replace('Рё СѓСЋС‚РѕРј.', 'Рё СѓСЋС‚РѕРј').replace('СЃРІРѕР№ РјР°СЂС€СЂСѓС‚.</i>', 'СЃРІРѕР№ РјР°СЂС€СЂСѓС‚</i>').replace('Р’Р Р•РњРЇ РџР РћР“РЈР›РљР</label>', '25 РР®Р›РЇ В· Р’Р Р•РњРЇ РџР РћР“РЈР›РљР</label>').replace('</body>', `<script>document.querySelector('#form').onsubmit=async e=>{e.preventDefault();if(!slot){alert('Р’С‹Р±РµСЂРё РІСЂРµРјСЏ РїСЂРѕРіСѓР»РєРё');return}const button=e.currentTarget.querySelector('.submit');button.disabled=true;try{const r=await fetch('/api/book',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slot,phone:document.querySelector('#phone').value,consent:document.querySelector('#consent').checked})});if(!r.ok)throw new Error();const s=document.querySelector('#success');s.hidden=false;s.textContent='РўС‹ Р·Р°РїРёСЃР°РЅ(Р°) РЅР° '+slot+'. РњС‹ СЃРІСЏР¶РµРјСЃСЏ СЃ С‚РѕР±РѕР№ РїРѕ СѓРєР°Р·Р°РЅРЅРѕРјСѓ РЅРѕРјРµСЂСѓ.';button.textContent='РўС‹ Р·Р°РїРёСЃР°РЅ(Р°) вЂ” РґРѕ РІСЃС‚СЂРµС‡Рё!'}catch{alert('РќРµ СѓРґР°Р»РѕСЃСЊ РѕС‚РїСЂР°РІРёС‚СЊ Р·Р°СЏРІРєСѓ. РџРѕРїСЂРѕР±СѓР№ РµС‰С‘ СЂР°Р· РїРѕР·Р¶Рµ.');button.disabled=false}}</script></body>`);
// Vercel serves files from public directly; keep this artifact alongside the
// existing Worker output so both hosting options use precisely the same page.
await writeFile('public/index.html', html);
await mkdir('dist/server', { recursive: true });
const worker = `const page=${JSON.stringify(html)};export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/book'&&request.method==='POST'){try{const data=await request.json();if(!data.slot||!data.phone||!data.consent)return Response.json({error:'invalid'},{status:400});if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return Response.json({error:'not configured'},{status:503});const text='РќРѕРІР°СЏ Р·Р°СЏРІРєР° вЂ” РќРµРјРµС†РєР°СЏ СЃР»РѕР±РѕРґР°\\nР”Р°С‚Р°: 25 РёСЋР»СЏ\\nР’СЂРµРјСЏ: '+data.slot+'\\nРўРµР»РµС„РѕРЅ: '+data.phone;const sent=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text})});if(!sent.ok)throw new Error('telegram');return Response.json({ok:true})}catch{return Response.json({error:'send failed'},{status:500})}}return new Response(page,{headers:{'content-type':'text/html; charset=UTF-8'}})}};`;
await writeFile('dist/server/index.js', worker);

